# Generated by Django 5.2.7 on 2025-11-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
            ],
        ),
    ]
