# Generated by Django 5.2.6 on 2025-11-04 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shift_date_shift_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
