# Generated by Django 5.2.8 on 2025-11-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_time_off_rename_cover_employee_id_shift_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
