# Generated by Django 5.2.8 on 2025-11-19 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_account_first_name_alter_account_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='time_off',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='time_off',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
