# Generated by Django 5.2.8 on 2025-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_account_first_name_alter_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='role',
            field=models.CharField(choices=[('MGR', 'Manager'), ('CK', 'Cook'), ('SVR', 'Server')], default='SVR'),
        ),
    ]
