# Generated by Django 5.2.8 on 2025-11-20 21:36

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_shift_date_shift_end_time_shift_start_time_timeoff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='date',
            new_name='request_date',
        ),
        migrations.RenameField(
            model_name='timeoff',
            old_name='date',
            new_name='request_date',
        ),
        migrations.AddField(
            model_name='timeoff',
            name='type',
            field=models.CharField(default='Unpaid'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(default=main.models.current_time),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.DateTimeField(default=main.models.current_time),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='end_time',
            field=models.DateTimeField(default=main.models.current_time),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='start_time',
            field=models.DateTimeField(default=main.models.current_time),
        ),
    ]
