# Generated by Django 5.2.8 on 2025-11-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_request_date_shift_date_alter_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoff',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
