# Generated by Django 5.2.6 on 2025-11-04 13:59

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='shift',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
