# Generated by Django 5.2.6 on 2025-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_time_shift_start_time_shift_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='role',
            field=models.CharField(choices=[('MGR', 'Manager'), ('CK', 'Cook'), ('SVR', 'Server')], default='Server'),
        ),
    ]
