# Generated by Django 5.2.6 on 2025-11-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_shift_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='cover_employee_id',
            field=models.IntegerField(default=0),
        ),
    ]
