# Generated by Django 5.2.7 on 2025-11-10 21:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_shift_cover_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('employee_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='cover_employee_id',
            new_name='employee_id',
        ),
    ]
