# Generated by Django 5.2.8 on 2025-11-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_shift_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='time_off',
            name='date',
        ),
        migrations.RemoveField(
            model_name='time_off',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='time_off',
            name='start_time',
        ),
    ]
