# Generated by Django 5.2.8 on 2025-11-19 18:05

import datetime
import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_shift_date_remove_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=main.models.current_time),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=main.models.current_time),
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=main.models.current_time)),
                ('end_time', models.TimeField(default=main.models.current_time)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='time_off',
        ),
    ]
