# Generated by Django 5.2.8 on 2025-11-20 21:41

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_date_shift_request_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='request_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=main.models.current_time),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=main.models.current_time),
        ),
    ]
