# Generated by Django 5.2.8 on 2025-12-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_timeoff_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('MGR', 'Manager'), ('CK', 'Cook'), ('SVR', 'Server')], max_length=20),
        ),
    ]
