# Generated by Django 5.2.8 on 2025-11-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_timeoff_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoff',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
