# Generated by Django 5.2.8 on 2025-11-25 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
