# Generated by Django 5.2.8 on 2025-12-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_account_account_type'),
        ('main', '0023_alter_availability_end_alter_availability_start'),
    ]

    operations = [
    ]
