# Generated by Django 5.2.8 on 2025-12-05 19:05

import django.db.models.deletion
import main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_availability_end_alter_availability_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start',
        ),
        migrations.AddField(
            model_name='availability',
            name='week',
            field=models.JSONField(default=main.default_week),
        ),
        migrations.AlterField(
            model_name='availability',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
