# Generated by Django 5.2.8 on 2025-12-08 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_merge_20251202_0806'),
        ('main', '0024_remove_availability_day_remove_availability_end_and_more'),
    ]

    operations = [
    ]
